---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/francesc2509/argocd-test.git
    targetRevision: HEAD
    path: lesson-158/my-app
  destination:
    server: https://kubernetes.default.svc
